version: "3.8"

services:
    strichliste:
        image: ghcr.io/strichliste/strichliste-docker:master
        build:
            context: .
        # if you use traefik you can remove the ports section
        ports:
            - 8080:8080
        networks:
            # - proxy  # your traefik network
            - default
        env_file:
            - docker.env
        volumes:
             - ./config/services.yaml:/source/config/services.yaml
             - ./config/strichliste.yaml:/source/config/strichliste.yaml
             - ./config/doctrine.yaml:/source/config/packages/doctrine.yaml

        environment:
            APP_ENV: "prod"

        # Traefik configuration
        # labels:
        #     - "traefik.docker.network={your traefik network}"
        #     - "traefik.frontend.rule=Host:{URL}"
        #     - "traefik.enable=true"
        #     - "traefik.port=8080"
    strichliste-db:
        image: mariadb:10.11.5
        restart: always
        networks:
            - default
        env_file:
            - docker.env
        volumes:
            - ./data/mysql:/var/lib/mysql

networks:
    proxy:
        external: true
